# Generated by Django 4.2.16 on 2025-10-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetModel",
            fields=[
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("STOCKS", "Stocks"),
                            ("RATES", "Interest Rates"),
                            ("FX", "Exchange Rates"),
                            ("CRYPTO", "Crypto Exchange Rates"),
                            ("COMMODITIES", "Commodities"),
                            ("OTHERS", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("US", "United States"),
                            ("EU", "Europe"),
                            ("DE", "Germany"),
                            ("FR", "France"),
                            ("JP", "Japan"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("short_name", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("maturity", models.FloatField(blank=True, null=True)),
                (
                    "asset_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EQUITY_INDEX", "Equity Index"),
                            ("INTERBANK_RATE", "Interbank Rate"),
                            ("GOVERNMENT_BOND_RATE", "Government Bond Rate"),
                            ("FX_SPOT_RATE", "FX Spot Rate"),
                            ("CRYPTO_SPOT_RATE", "Cryptocurrency Spot Rate"),
                            (
                                "COMMODITIY_FUTURE_SPOT_PRICE",
                                "Commodity Future Spot Price",
                            ),
                            ("VOLATILITY_INDEX", "Volatility Index"),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ticker", models.CharField(max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GOV_TREASURY_DEPT", "US Treasury Department"),
                            ("NYFED", "New York Federal Reserve"),
                            ("FRED", "Federal Reserve Bank of St Louis"),
                            ("WEBSTAT", "Webstat, Banque de France"),
                            ("BUNDESBANK", "Deutsche Bundesbank"),
                            ("BOJ", "Bank of Japan"),
                            ("BB", "Japan Bond Trading"),
                            ("GLOBAL_RATES", "GlobalRates.com"),
                            ("YAHOO", "Yahoo Finance"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketPriceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("price", models.FloatField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="", null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="market_overview.assetmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PriceUpdateLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("logs", models.TextField()),
                (
                    "market_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_update_logs",
                        to="market_overview.marketpricemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
                "abstract": False,
            },
        ),
    ]
