# Generated by Django 4.2.16 on 2025-10-23 19:30

from django.db import migrations, models, transaction
import django.db.models.deletion


def copy_short_name_to_temp(apps, schema_editor):
    MarketPrice = apps.get_model("market_overview", "MarketPriceModel")
    with transaction.atomic():
        for market_price in MarketPrice.objects.select_related("asset").all():
            market_price.asset_short_name_temp = market_price.asset.short_name
            market_price.save(update_fields=["asset_short_name_temp"])


def populate_new_fk(apps, schema_editor):
    MarketPrice = apps.get_model("market_overview", "MarketPriceModel")
    with transaction.atomic():
        for market_price in MarketPrice.objects.all():
            market_price.asset_id = market_price.asset_short_name_temp
            market_price.save(update_fields=["asset"])


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketpricemodel",
            name="asset_short_name_temp",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(
            copy_short_name_to_temp, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="marketpricemodel",
            name="asset",
        ),
        migrations.AlterField(
            model_name="assetmodel",
            name="id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="assetmodel",
            name="short_name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="marketpricemodel",
            name="asset",
            field=models.ForeignKey(
                db_column="asset_short_name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_prices",
                to="market_overview.assetmodel",
                to_field="short_name",
            ),
        ),
        migrations.RunPython(populate_new_fk, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="marketpricemodel",
            name="asset",
            field=models.ForeignKey(
                db_column="asset_short_name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_prices",
                to="market_overview.assetmodel",
                to_field="short_name",
            ),
        ),
        migrations.RemoveField(
            model_name="marketpricemodel",
            name="asset_short_name_temp",
        ),
    ]
