# Generated by Django 4.2.16 on 2025-11-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0002_asset_short_name_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketpricemodel",
            name="asset",
            field=models.ForeignKey(
                db_column="asset_short_name",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_prices",
                to="market_overview.assetmodel",
            ),
        ),
    ]
