# Generated by Django 4.1.7 on 2025-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0002_marketpricemodel_maturity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketpricemodel",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("STOCKS", "Stocks"),
                    ("CB_RATES", "Central Bank Policy Rate"),
                    ("RATES", "Interest Rates"),
                    ("FX", "Exchange Rates"),
                    ("CRYPTO", "Crypto Exchange Rates"),
                    ("COMMODITIES", "Commodities"),
                    ("OTHERS", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="marketpricemodel",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[("US", "US"), ("EU", "EU"), ("JP", "JP"), ("UK", "UK")],
                max_length=2,
                null=True,
            ),
        ),
    ]
