# Generated by Django 4.2.16 on 2025-11-14 16:15

from django.db import migrations, models


def copy_id_to_asset_id(apps, schema_editor):
    """Copy id field values to asset_id for existing records."""
    AssetModel = apps.get_model("market_overview", "AssetModel")
    counter = 1
    for asset in AssetModel.objects.all():
        # Get the id value if it exists and is valid
        old_id = getattr(asset, "id", None)
        if old_id is not None and old_id != "":
            try:
                asset.asset_id = int(old_id)
            except (ValueError, TypeError):
                # If id is invalid, assign a sequential number
                asset.asset_id = counter
                counter += 1
        else:
            # If id is missing or empty, assign a sequential number
            asset.asset_id = counter
            counter += 1
        asset.save(update_fields=["asset_id"])


def reverse_copy_id_to_asset_id(apps, schema_editor):
    """Reverse operation - not needed as we're removing id field."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0003_alter_marketpricemodel_asset"),
    ]

    operations = [
        # Step 1: Add asset_id as nullable first
        migrations.AddField(
            model_name="assetmodel",
            name="asset_id",
            field=models.IntegerField(null=True, blank=True),
        ),
        # Step 2: Copy data from id to asset_id
        migrations.RunPython(copy_id_to_asset_id, reverse_copy_id_to_asset_id),
        # Step 3: Make asset_id non-nullable
        migrations.AlterField(
            model_name="assetmodel",
            name="asset_id",
            field=models.IntegerField(),
        ),
        # Step 4: Remove the old id field
        migrations.RemoveField(
            model_name="assetmodel",
            name="id",
        ),
    ]
