# Generated by Django 4.2.16 on 2025-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0004_remove_assetmodel_id_assetmodel_asset_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmodel",
            name="source",
            field=models.CharField(
                choices=[
                    ("GOV_TREASURY_DEPT", "US Treasury Department"),
                    ("NYFED", "New York Federal Reserve"),
                    ("WEBSTAT", "Webstat, Banque de France"),
                    ("BUNDESBANK", "Deutsche Bundesbank"),
                    ("BOJ", "Bank of Japan"),
                    ("BB", "Japan Bond Trading"),
                    ("GLOBAL_RATES", "GlobalRates.com"),
                    ("YAHOO", "Yahoo Finance"),
                ],
                max_length=100,
            ),
        ),
    ]
