# Generated by Django 4.1.7 on 2025-10-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0005_alter_marketpricemodel_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="priceupdatelogmodel",
            options={"ordering": ["-date_added"]},
        ),
        migrations.RenameField(
            model_name="priceupdatelogmodel",
            old_name="created_at",
            new_name="date_added",
        ),
        migrations.AddField(
            model_name="priceupdatelogmodel",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
