# Generated by Django 4.2.16 on 2025-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0005_alter_assetmodel_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("EU", "Europe"),
                            ("DE", "Germany"),
                            ("FR", "France"),
                            ("JP", "Japan"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
