# Generated by Django 4.2.16 on 2026-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0006_holidaymodel"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="marketpricemodel",
            constraint=models.UniqueConstraint(
                fields=("asset", "date"), name="unique_market_price_per_asset_date"
            ),
        ),
    ]
