# Generated by Django 4.1.7 on 2025-10-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0008_remove_marketpricemodel_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketpricemodel",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EQUITY_INDEX", "Equity Index"),
                    ("CB_TARGET_RATE", "Central Bank Policy Rate"),
                    ("INTERBANK_RATE", "Interbank Rate"),
                    ("GOVERNMENT_BOND_RATE", "Government Bond Rate"),
                    ("FX_SPOT_RATE", "FX Spot Rate"),
                    ("CRYPTO_SPOT_RATE", "Cryptocurrency Spot Rate"),
                    ("COMMODITIY_FUTURE_SPOT_PRICE", "Commodity Future Spot Price"),
                    ("VOLATILITY_INDEX", "Volatility Index"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
