# Generated by Django 4.1.7 on 2025-10-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0010_rename_comment_priceupdatelogmodel_logs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketpricemodel",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("EU", "Europe"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("JP", "Japan"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketpricemodel",
            name="source",
            field=models.CharField(
                choices=[
                    ("GOV_TREASURY_DEPT", "US Treasury Department"),
                    ("NYFED", "New York Federal Reserve"),
                    ("FRED", "Federal Reserve Bank of St Louis"),
                    ("WEBSTAT", "Webstat, Banque de France"),
                    ("BUNDESBANK", "Deutsche Bundesbank"),
                    ("BOJ", "Bank of Japan"),
                    ("BB", "Japan Bond Trading"),
                    ("GLOBAL_RATES", "GlobalRates.com"),
                    ("YAHOO", "Yahoo Finance"),
                ],
                max_length=100,
            ),
        ),
    ]
