# Generated by Django 4.2.16 on 2025-10-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0011_alter_marketpricemodel_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketpricemodel",
            name="comment",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
