# Generated by Django 4.2.16 on 2025-10-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_overview", "0012_marketpricemodel_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketpricemodel",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("STOCKS", "Stocks"),
                    ("RATES", "Interest Rates"),
                    ("FX", "Exchange Rates"),
                    ("CRYPTO", "Crypto Exchange Rates"),
                    ("COMMODITIES", "Commodities"),
                    ("OTHERS", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="marketpricemodel",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EQUITY_INDEX", "Equity Index"),
                    ("INTERBANK_RATE", "Interbank Rate"),
                    ("GOVERNMENT_BOND_RATE", "Government Bond Rate"),
                    ("FX_SPOT_RATE", "FX Spot Rate"),
                    ("CRYPTO_SPOT_RATE", "Cryptocurrency Spot Rate"),
                    ("COMMODITIY_FUTURE_SPOT_PRICE", "Commodity Future Spot Price"),
                    ("VOLATILITY_INDEX", "Volatility Index"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
