# Generated by Django 4.1.7 on 2025-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketPriceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("STOCKS", "STOCKS"),
                            ("RATES", "RATES"),
                            ("FX", "FX"),
                            ("CRYPTO", "CRYPTO"),
                            ("COMMODITIES", "COMMODITIES"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("US", "US"),
                            ("EU", "EU"),
                            ("JP", "JP"),
                            ("UK", "UK"),
                        ],
                        max_length=2,
                    ),
                ),
                ("short_name", models.CharField(default="", max_length=100)),
                ("full_name", models.CharField(default="", max_length=100)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GOV_TREASURY_DEPT", "US Treasury Department"),
                            ("NYFED", "New York Federal Reserve"),
                            ("WEBSTAT", "Webstat, Banque de France"),
                            ("GLOBAL_RATES", "GlobalRates.com"),
                            ("YAHOO", "Yahoo Finance"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
