# Generated by Django 4.1.7 on 2025-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketpricemodel",
            name="maturity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketpricemodel",
            name="source",
            field=models.CharField(
                choices=[
                    ("GOV_TREASURY_DEPT", "US Treasury Department"),
                    ("NYFED", "New York Federal Reserve"),
                    ("FRED", "Federal Reserve Bank of St Louis"),
                    ("WEBSTAT", "Webstat, Banque de France"),
                    ("BUNDESBANK", "Deutsche Bundesbank"),
                    ("BOS", "Banco de Espana"),
                    ("BOJ", "Bank of Japan"),
                    ("BB", "Japan Bond Trading"),
                    ("GLOBAL_RATES", "GlobalRates.com"),
                    ("YAHOO", "Yahoo Finance"),
                ],
                max_length=100,
            ),
        ),
    ]
