# Generated by Django 4.1.7 on 2025-10-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_data", "0003_alter_marketpricemodel_asset_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketpricemodel",
            name="update_comments",
            field=models.CharField(
                blank=True, default=None, max_length=10000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketpricemodel",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("STOCKS", "Stocks"),
                    ("RATES", "Interest Rates"),
                    ("FX", "Exchange Rates"),
                    ("CRYPTO", "Crypto Exchange Rates"),
                    ("COMMODITIES", "Commodities"),
                    ("OTHERS", "Others"),
                    ("CB_RATES", "Central Bank Policy Rate"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="marketpricemodel",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "US"),
                    ("EU", "EU"),
                    ("DE", "DE"),
                    ("FR", "FR"),
                    ("SP", "SP"),
                    ("JP", "JP"),
                    ("UK", "UK"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
