# Generated by Django 4.1.7 on 2025-10-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_data", "0004_marketpricemodel_update_comments_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marketpricemodel",
            unique_together={("short_name", "date")},
        ),
        migrations.CreateModel(
            name="PriceUpdateLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_logs",
                        to="scrap_data.marketpricemodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="marketpricemodel",
            name="update_comments",
        ),
    ]
