# Generated by Django 4.1.7 on 2025-10-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_data", "0006_alter_priceupdatelogmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketpricemodel",
            name="comment",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
