# Generated by Django 4.1.7 on 2025-10-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_data", "0007_marketpricemodel_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketpricemodel",
            name="comment",
        ),
    ]
