# Generated by Django 4.1.7 on 2025-10-07 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrap_data", "0009_marketpricemodel_asset_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="priceupdatelogmodel",
            old_name="comment",
            new_name="logs",
        ),
        migrations.AlterField(
            model_name="priceupdatelogmodel",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_update_logs",
                to="scrap_data.marketpricemodel",
            ),
        ),
    ]
