# Generated by Django 4.2.16 on 2025-10-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomicDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("period", models.DateField()),
                ("data_value", models.FloatField(blank=True, null=True)),
                ("publication_date", models.DateField()),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EconomicIndicatorInformationModel",
            fields=[
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("EU", "Europe"),
                            ("FR", "France"),
                            ("JP", "Japan"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GROWTH", "Growth"),
                            ("INFLATION", "Inflation"),
                            ("GOVERNMENT", "Government"),
                            ("LABOUR", "Labour"),
                            ("HOUSING", "Housing"),
                            ("PRODUCTION", "Production"),
                            ("CONFIDENCE", "Confidence"),
                            ("SALES", "Sales"),
                            ("CENTRAL_BANKS", "Central Banks"),
                        ],
                        max_length=255,
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("technical_name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(choices=[("INSEE", "INSEE")], max_length=255),
                ),
                ("ticker_id", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EconomicDataUpdateLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("logs", models.TextField()),
                (
                    "economic_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economic_data_update_logs",
                        to="economic_overview.economicdatamodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="economicdatamodel",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="economic_data",
                to="economic_overview.economicindicatorinformationmodel",
            ),
        ),
    ]
