# Generated by Django 4.2.16 on 2025-10-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("economic_overview", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="economicindicatorinformationmodel",
            old_name="ticker_id",
            new_name="ticker",
        ),
        migrations.CreateModel(
            name="PublicationScheduleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIOUS", "Previous"),
                            ("CURRENT", "Current"),
                            ("NEXT", "Next"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_schedule",
                        to="economic_overview.economicindicatorinformationmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
