# Generated by Django 4.2.16 on 2025-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "economic_overview",
            "0002_rename_ticker_id_economicindicatorinformationmodel_ticker_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicdatamodel",
            name="period",
            field=models.CharField(max_length=255),
        ),
    ]
