# Generated by Django 4.2.16 on 2025-10-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("economic_overview", "0003_alter_economicdatamodel_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="economicdatamodel",
            name="publication_date",
        ),
    ]
