# Generated by Django 4.2.16 on 2025-10-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economic_overview", "0004_remove_economicdatamodel_publication_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicationschedulemodel",
            old_name="publication_date",
            new_name="current_publication_date",
        ),
        migrations.RemoveField(
            model_name="publicationschedulemodel",
            name="status",
        ),
        migrations.AddField(
            model_name="publicationschedulemodel",
            name="next_publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationschedulemodel",
            name="previous_publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
