# Generated by Django 4.2.16 on 2025-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "economic_overview",
            "0005_rename_publication_date_publicationschedulemodel_current_publication_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicdatamodel",
            name="period",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="economicindicatorinformationmodel",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("ANNUAL", "Annual"),
                ],
                max_length=255,
            ),
        ),
    ]
