# Generated by Django 4.2.16 on 2025-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economic_overview", "0006_alter_economicdatamodel_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationschedulemodel",
            name="current_publication_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationschedulemodel",
            name="next_publication_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationschedulemodel",
            name="previous_publication_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
