# Generated by Django 4.2.16 on 2025-10-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economic_overview", "0007_add_datetime_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicationschedulemodel",
            name="current_publication_datetime",
        ),
        migrations.RemoveField(
            model_name="publicationschedulemodel",
            name="next_publication_datetime",
        ),
        migrations.RemoveField(
            model_name="publicationschedulemodel",
            name="previous_publication_datetime",
        ),
        migrations.AlterField(
            model_name="publicationschedulemodel",
            name="current_publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicationschedulemodel",
            name="next_publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicationschedulemodel",
            name="previous_publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
