# Generated by Django 4.2.16 on 2025-11-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economic_overview", "0008_change_date_to_datetime_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicindicatorinformationmodel",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("ANNUAL", "Annual"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="economicindicatorinformationmodel",
            name="source",
            field=models.CharField(
                choices=[
                    ("INSEE", "INSEE"),
                    ("JP_CABINET_OFFICE", "Japan Cabinet Office"),
                ],
                max_length=255,
            ),
        ),
    ]
