"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

import environ
from celery.schedules import crontab

from core.open_api import ApiTags

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ and read .env file
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0", "webapp"]

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "rest_framework",
    "drf_spectacular",
    "market_overview.apps.MarketOverviewConfig",
    "data_visualization.apps.DataVisualizationConfig",
    "economic_overview.apps.EconomicOverviewConfig",
    "central_banks_overview.apps.CentralBanksOverviewConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"


# Celery Configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule (Periodic Tasks)
CELERY_BEAT_SCHEDULE = {
    "scheduled-market-data-ingestion-morning": {
        "task": "market_overview.tasks.scheduled_market_data_ingestion",
        "schedule": crontab(day_of_week="1-5", hour="8", minute="0"),
    },
    "scheduled-market-data-ingestion-afternoon": {
        "task": "market_overview.tasks.scheduled_market_data_ingestion",
        "schedule": crontab(day_of_week="1-5", hour="14", minute="0"),
    },
    "scheduled-market-data-ingestion-evening": {
        "task": "market_overview.tasks.scheduled_market_data_ingestion",
        "schedule": crontab(day_of_week="1-5", hour="20", minute="0"),
    },
    "scheduled-stir-prices-ingestion-morning": {
        "task": "central_banks_overview.tasks.scheduled_stir_prices_ingestion",
        "schedule": crontab(day_of_week="1-5", hour="8", minute="0"),
    },
    "scheduled-stir-prices-ingestion-evening": {
        "task": "central_banks_overview.tasks.scheduled_stir_prices_ingestion",
        "schedule": crontab(day_of_week="1-5", hour="20", minute="40"),
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "Market Watch API",
    "DESCRIPTION": "Personal API to monitor markets based on market data and economic indicators scrapping.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/",
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
    "SORT_OPERATIONS": False,
    "ENUM_NAME_OVERRIDES": {
        "AssetClassChoices": "market_overview.models.AssetClassChoices",
        "AssetTypeChoices": "market_overview.models.AssetTypeChoices",
        "LocationChoices": "market_overview.models.LocationChoices",
    },
    "TAGS": [
        {
            "name": ApiTags.ASSETS.value,
            "description": "Asset data related endpoints",
        },
        {
            "name": ApiTags.ASSET_PRICES.value,
            "description": "Market data related endpoints",
        },
        {
            "name": ApiTags.ECONOMIC_INDICATOR_INFORMATION.value,
            "description": "Economic indicator information related endpoints",
        },
        {
            "name": ApiTags.ECONOMIC_DATA.value,
            "description": "Economic data related endpoints",
        },
        {
            "name": ApiTags.PUBLICATION_SCHEDULE.value,
            "description": "Economic publication schedule related endpoints",
        },
        {
            "name": ApiTags.CENTRAL_BANKS.value,
            "description": "Central banks related endpoints",
        },
        {
            "name": ApiTags.LOGS.value,
            "description": "Endpoints to get change logs",
        },
    ],
}


# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "clean": {
            "format": "{levelname} {asctime}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "clean",
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
