# Generated by Django 4.2.16 on 2025-11-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentralBankDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "cb_data_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "central_bank",
                    models.CharField(
                        choices=[
                            ("FRB", "Federal Reserve (FRB)"),
                            ("BOJ", "Bank of Japan (BOJ)"),
                            ("ECB", "European Central Bank (ECB)"),
                        ],
                        max_length=255,
                    ),
                ),
                ("short_name", models.CharField(default="", max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("value", models.FloatField(blank=True, default=None, null=True)),
                ("comment", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CentralBankMeetingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "central_bank",
                    models.CharField(
                        choices=[
                            ("FRB", "Federal Reserve (FRB)"),
                            ("BOJ", "Bank of Japan (BOJ)"),
                            ("ECB", "European Central Bank (ECB)"),
                        ],
                        max_length=255,
                    ),
                ),
                ("order", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StirFuturesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "central_bank",
                    models.CharField(
                        choices=[
                            ("FRB", "Federal Reserve (FRB)"),
                            ("BOJ", "Bank of Japan (BOJ)"),
                            ("ECB", "European Central Bank (ECB)"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        choices=[
                            ("FF1M", "1 Month Fed Funds STIR Futures"),
                            ("ESTR3M", "3 Month ESTR Futures"),
                            ("MUTAN3M", "3 Month Mutan STIR Futures"),
                        ],
                        max_length=255,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("maturity", models.TextField(blank=True, null=True)),
                (
                    "first_accrual_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "last_accrual_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("date", models.DateField()),
                ("price", models.FloatField(blank=True, default=None, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("YAHOO", "Yahoo Finance"),
                            ("TFX", "TFX"),
                            ("PDF", "PDF"),
                        ],
                        max_length=255,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StirFuturesPriceUpdateLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("logs", models.TextField()),
                (
                    "stir_futures",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stir_futures_price_update_logs",
                        to="central_banks_overview.stirfuturesmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
                "abstract": False,
            },
        ),
    ]
