# Generated by Django 4.2.16 on 2025-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central_banks_overview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centralbankdatamodel",
            name="central_bank",
            field=models.CharField(
                choices=[
                    ("FRB", "Federal Reserve (FRB)"),
                    ("BOJ", "Bank of Japan (BOJ)"),
                    ("ECB", "European Central Bank (ECB)"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="centralbankdatamodel",
            name="short_name",
            field=models.CharField(
                choices=[
                    ("FEDFUNDS", "FRB Target Fed Funds Rate"),
                    ("ESTR", "ECB Target Overnight Rate"),
                    ("ECB_DEPOSIT", "ECB Deposit Facility Rate"),
                    ("ECB_REFINANCING", "ECB Main Refinancing Operation Rate"),
                    ("ECB_MARGINAL_LENDING", "ECB Marginal Lending Facility Rate"),
                    ("MUTAN", "BOJ Target Uncollateralized Overnight Rate"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="centralbankmeetingmodel",
            name="central_bank",
            field=models.CharField(
                choices=[
                    ("FRB", "Federal Reserve (FRB)"),
                    ("BOJ", "Bank of Japan (BOJ)"),
                    ("ECB", "European Central Bank (ECB)"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="stirfuturesmodel",
            name="central_bank",
            field=models.CharField(
                choices=[
                    ("FRB", "Federal Reserve (FRB)"),
                    ("BOJ", "Bank of Japan (BOJ)"),
                    ("ECB", "European Central Bank (ECB)"),
                ],
                max_length=255,
            ),
        ),
    ]
