# Generated by Django 4.2.16 on 2025-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "central_banks_overview",
            "0002_alter_centralbankdatamodel_central_bank_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centralbankdatamodel",
            name="id",
        ),
        migrations.AddField(
            model_name="centralbankdatamodel",
            name="cb_data_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="centralbankdatamodel",
            name="short_name",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
