# Generated by Django 4.2.16 on 2025-11-17 18:04

from django.db import migrations, models


def populate_id_field(apps, schema_editor):
    """Populate id field with sequential values for existing records."""
    CentralBankDataModel = apps.get_model(
        "central_banks_overview", "CentralBankDataModel"
    )
    counter = 1
    for record in CentralBankDataModel.objects.all().order_by("short_name"):
        record.id = counter
        record.save(update_fields=["id"])
        counter += 1


def reverse_populate_id_field(apps, schema_editor):
    """Reverse operation - not needed as we're adding id field."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("central_banks_overview", "0003_remove_centralbankdatamodel_id_and_more"),
    ]

    operations = [
        # Step 1: Add id as nullable IntegerField (not primary key yet)
        migrations.AddField(
            model_name="centralbankdatamodel",
            name="id",
            field=models.IntegerField(null=True, blank=True),
        ),
        # Step 2: Populate id with sequential values
        migrations.RunPython(populate_id_field, reverse_populate_id_field),
        # Step 3: Remove primary key from short_name
        migrations.AlterField(
            model_name="centralbankdatamodel",
            name="short_name",
            field=models.CharField(default="", max_length=255),
        ),
        # Step 4: Convert id to BigAutoField and make it primary key
        migrations.AlterField(
            model_name="centralbankdatamodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
